[platformio]
default_envs = cyd

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bodmer/TFT_eSPI@^2.5.33
    https://github.com/PaulStoffregen/XPT2046_Touchscreen.git#v1.4
    knolleary/PubSubClient@^2.8
    bblanchon/ArduinoJson@^6.21.3

[env:cyd]
build_flags =
    -DUSER_SETUP_LOADED
    -DUSE_HSPI_PORT
    -DTFT_MISO=12
    -DTFT_MOSI=13
    -DTFT_SCLK=14
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=-1
    -DTFT_BL=21
    -DTOUCH_CS=33
    -DTFT_BACKLIGHT_ON=HIGH
    -DSPI_FREQUENCY=55000000
    -DSPI_READ_FREQUENCY=20000000
    -DSPI_TOUCH_FREQUENCY=2500000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_FONT8
    -DLOAD_GFXFF
    -DILI9341_DRIVER

[env:sensor]
build_flags =
    -DUSE_HSPI_PORT